<p>index of authorizations</p>
<table class="auths">
 <col class="checkbox" />
 <col class="email" />
 <col class="client" />
 <col class="context" />
 <col class="roles" />
 <thead>
  <tr>
     <th></th>
     <th>User E-mail</th>
     <th>Client</th>
     <th>Context</th>
     <th>Roles</th>
  </tr>
 </thead>
 <tbody></tbody>
</table>
<form>
  <input type="button" value="delete" class="button delete" />
</form>
